/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

/**
 *
 * @author Anonymous
 */
public class courseManagement extends javax.swing.JFrame {

    /**
     * Creates new form courseManagement
     */
    public courseManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        whitePanel8 = new javax.swing.JPanel();
        coursemanagementHeading7 = new javax.swing.JLabel();
        courseIDLabel7 = new javax.swing.JLabel();
        courseIDField7 = new javax.swing.JTextField();
        depIDLabel7 = new javax.swing.JLabel();
        depIDField7 = new javax.swing.JTextField();
        courseNameLabel7 = new javax.swing.JLabel();
        courseNameField7 = new javax.swing.JTextField();
        newCourseButton7 = new javax.swing.JButton();
        editCourseButton7 = new javax.swing.JButton();
        deleteCourseButton7 = new javax.swing.JButton();
        resetCourseButton7 = new javax.swing.JButton();
        closeButton7 = new javax.swing.JButton();
        studentsTable7 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setToolTipText("");

        coursemanagementHeading7.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        coursemanagementHeading7.setForeground(new java.awt.Color(0, 51, 102));
        coursemanagementHeading7.setText("Manage Courses");

        courseIDLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        courseIDLabel7.setForeground(new java.awt.Color(0, 51, 102));
        courseIDLabel7.setText("CourseID :");

        depIDLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        depIDLabel7.setForeground(new java.awt.Color(0, 51, 102));
        depIDLabel7.setText("Department :");

        courseNameLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        courseNameLabel7.setForeground(new java.awt.Color(0, 51, 102));
        courseNameLabel7.setText("Course :");

        newCourseButton7.setBackground(new java.awt.Color(0, 51, 102));
        newCourseButton7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        newCourseButton7.setForeground(new java.awt.Color(204, 204, 204));
        newCourseButton7.setText("New");
        newCourseButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editCourseButton7.setBackground(new java.awt.Color(0, 51, 102));
        editCourseButton7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        editCourseButton7.setForeground(new java.awt.Color(204, 204, 204));
        editCourseButton7.setText("Edit");
        editCourseButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteCourseButton7.setBackground(new java.awt.Color(0, 51, 102));
        deleteCourseButton7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        deleteCourseButton7.setForeground(new java.awt.Color(204, 204, 204));
        deleteCourseButton7.setText("Delete");
        deleteCourseButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        resetCourseButton7.setBackground(new java.awt.Color(0, 51, 102));
        resetCourseButton7.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        resetCourseButton7.setForeground(new java.awt.Color(204, 204, 204));
        resetCourseButton7.setText("Reset");
        resetCourseButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        closeButton7.setBackground(new java.awt.Color(0, 51, 102));
        closeButton7.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        closeButton7.setForeground(new java.awt.Color(255, 255, 255));
        closeButton7.setText("X");
        closeButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButton7MouseClicked(evt);
            }
        });

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseID", "Department", "Course"
            }
        ));
        jTable8.setRowHeight(20);
        studentsTable7.setViewportView(jTable8);

        javax.swing.GroupLayout whitePanel8Layout = new javax.swing.GroupLayout(whitePanel8);
        whitePanel8.setLayout(whitePanel8Layout);
        whitePanel8Layout.setHorizontalGroup(
            whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitePanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton7))
            .addGroup(whitePanel8Layout.createSequentialGroup()
                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(whitePanel8Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(whitePanel8Layout.createSequentialGroup()
                                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depIDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseIDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depIDField7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseNameField7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseIDField7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(studentsTable7, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursemanagementHeading7, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(whitePanel8Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(newCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        whitePanel8Layout.setVerticalGroup(
            whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitePanel8Layout.createSequentialGroup()
                .addComponent(closeButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(coursemanagementHeading7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseIDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseIDField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depIDField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depIDLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(whitePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(studentsTable7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(whitePanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(whitePanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButton7MouseClicked
        setVisible(false);
        new adminDashboard().setVisible(true);
    }//GEN-LAST:event_closeButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton closeButton2;
    private javax.swing.JButton closeButton3;
    private javax.swing.JButton closeButton4;
    private javax.swing.JButton closeButton5;
    private javax.swing.JButton closeButton6;
    private javax.swing.JButton closeButton7;
    private javax.swing.JTextField courseIDField;
    private javax.swing.JTextField courseIDField1;
    private javax.swing.JTextField courseIDField2;
    private javax.swing.JTextField courseIDField3;
    private javax.swing.JTextField courseIDField4;
    private javax.swing.JTextField courseIDField5;
    private javax.swing.JTextField courseIDField6;
    private javax.swing.JTextField courseIDField7;
    private javax.swing.JLabel courseIDLabel;
    private javax.swing.JLabel courseIDLabel1;
    private javax.swing.JLabel courseIDLabel2;
    private javax.swing.JLabel courseIDLabel3;
    private javax.swing.JLabel courseIDLabel4;
    private javax.swing.JLabel courseIDLabel5;
    private javax.swing.JLabel courseIDLabel6;
    private javax.swing.JLabel courseIDLabel7;
    private javax.swing.JTextField courseNameField;
    private javax.swing.JTextField courseNameField1;
    private javax.swing.JTextField courseNameField2;
    private javax.swing.JTextField courseNameField3;
    private javax.swing.JTextField courseNameField4;
    private javax.swing.JTextField courseNameField5;
    private javax.swing.JTextField courseNameField6;
    private javax.swing.JTextField courseNameField7;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JLabel courseNameLabel1;
    private javax.swing.JLabel courseNameLabel2;
    private javax.swing.JLabel courseNameLabel3;
    private javax.swing.JLabel courseNameLabel4;
    private javax.swing.JLabel courseNameLabel5;
    private javax.swing.JLabel courseNameLabel6;
    private javax.swing.JLabel courseNameLabel7;
    private javax.swing.JLabel coursemanagementHeading;
    private javax.swing.JLabel coursemanagementHeading1;
    private javax.swing.JLabel coursemanagementHeading2;
    private javax.swing.JLabel coursemanagementHeading3;
    private javax.swing.JLabel coursemanagementHeading4;
    private javax.swing.JLabel coursemanagementHeading5;
    private javax.swing.JLabel coursemanagementHeading6;
    private javax.swing.JLabel coursemanagementHeading7;
    private javax.swing.JButton deleteCourseButton;
    private javax.swing.JButton deleteCourseButton1;
    private javax.swing.JButton deleteCourseButton2;
    private javax.swing.JButton deleteCourseButton3;
    private javax.swing.JButton deleteCourseButton4;
    private javax.swing.JButton deleteCourseButton5;
    private javax.swing.JButton deleteCourseButton6;
    private javax.swing.JButton deleteCourseButton7;
    private javax.swing.JTextField depIDField;
    private javax.swing.JTextField depIDField1;
    private javax.swing.JTextField depIDField2;
    private javax.swing.JTextField depIDField3;
    private javax.swing.JTextField depIDField4;
    private javax.swing.JTextField depIDField5;
    private javax.swing.JTextField depIDField6;
    private javax.swing.JTextField depIDField7;
    private javax.swing.JLabel depIDLabel;
    private javax.swing.JLabel depIDLabel1;
    private javax.swing.JLabel depIDLabel2;
    private javax.swing.JLabel depIDLabel3;
    private javax.swing.JLabel depIDLabel4;
    private javax.swing.JLabel depIDLabel5;
    private javax.swing.JLabel depIDLabel6;
    private javax.swing.JLabel depIDLabel7;
    private javax.swing.JButton editCourseButton;
    private javax.swing.JButton editCourseButton1;
    private javax.swing.JButton editCourseButton2;
    private javax.swing.JButton editCourseButton3;
    private javax.swing.JButton editCourseButton4;
    private javax.swing.JButton editCourseButton5;
    private javax.swing.JButton editCourseButton6;
    private javax.swing.JButton editCourseButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JButton newCourseButton;
    private javax.swing.JButton newCourseButton1;
    private javax.swing.JButton newCourseButton2;
    private javax.swing.JButton newCourseButton3;
    private javax.swing.JButton newCourseButton4;
    private javax.swing.JButton newCourseButton5;
    private javax.swing.JButton newCourseButton6;
    private javax.swing.JButton newCourseButton7;
    private javax.swing.JButton resetCourseButton;
    private javax.swing.JButton resetCourseButton1;
    private javax.swing.JButton resetCourseButton2;
    private javax.swing.JButton resetCourseButton3;
    private javax.swing.JButton resetCourseButton4;
    private javax.swing.JButton resetCourseButton5;
    private javax.swing.JButton resetCourseButton6;
    private javax.swing.JButton resetCourseButton7;
    private javax.swing.JScrollPane studentsTable;
    private javax.swing.JScrollPane studentsTable1;
    private javax.swing.JScrollPane studentsTable2;
    private javax.swing.JScrollPane studentsTable3;
    private javax.swing.JScrollPane studentsTable4;
    private javax.swing.JScrollPane studentsTable5;
    private javax.swing.JScrollPane studentsTable6;
    private javax.swing.JScrollPane studentsTable7;
    private javax.swing.JPanel whitePanel1;
    private javax.swing.JPanel whitePanel2;
    private javax.swing.JPanel whitePanel3;
    private javax.swing.JPanel whitePanel4;
    private javax.swing.JPanel whitePanel5;
    private javax.swing.JPanel whitePanel6;
    private javax.swing.JPanel whitePanel7;
    private javax.swing.JPanel whitePanel8;
    // End of variables declaration//GEN-END:variables
}
